# Generated by Django 5.2.8 on 2025-11-20 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL da Imagem')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(default='v1.0', max_length=50, verbose_name='Versão do Modelo')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Pontuação de Confiança')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('recommended_products', models.ManyToManyField(to='recommendations.product', verbose_name='Produtos Recomendados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Visualização'), ('click', 'Clique'), ('purchase', 'Compra'), ('rating', 'Avaliação')], max_length=20, verbose_name='Tipo de Interação')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Avaliação (1-5)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.product', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Interação do Usuário',
                'verbose_name_plural': 'Interações dos Usuários',
                'ordering': ['-timestamp'],
            },
        ),
    ]
